spring:
  profiles:
    active: dev
  #关闭缓存，随时刷新
  freemarker:
    cache: false
  #页面热部署
  thymeleaf:
    cache: true
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录，添加哪个目录的文件需要restart
      additional-paths: src/main/java
      #排除哪个目录的文件不需要restart
      #exclued: static/**,public/**
      #classpath目录下的WEB-INF文件夹内容修改不重启
      #exclued: WEB-INF/**
